# Generated by Django 5.0.3 on 2024-04-16 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("object_type", models.CharField(max_length=255)),
                ("given_name", models.CharField(max_length=255)),
                ("family_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("company_id", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("invite_url", models.URLField(blank=True, null=True)),
                ("avatar_image_url", models.URLField(blank=True, null=True)),
                ("first_login_date", models.DateTimeField(blank=True, null=True)),
                ("last_login_date", models.DateTimeField(blank=True, null=True)),
                ("creation_method", models.CharField(max_length=255)),
                ("custom_fields", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Paid", "Paid"),
                            ("Overdue", "Overdue"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("shared_on", models.DateTimeField(auto_now_add=True)),
                (
                    "send_email",
                    models.BooleanField(default=False, verbose_name="Send Email"),
                ),
                ("file", models.FileField(upload_to="invoices/")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pixelplan.client",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["shared_on"],
            },
        ),
    ]
